In [1]:
import pandas as pd

In [2]:
df_part1 = pd.read_csv("Data_Exercises/world-data-2023_part1.csv", index_col = 0)
df_part2 = pd.read_csv("Data_Exercises/world-data-2023_part2.csv", index_col = 0)

In [3]:
df_part1

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

In [4]:
df_part2

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,"$482,359,318,768",97.20%,79.30%,21.4,Caracas,72.1,125.0,$0.01,Spanish,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",Venezuela,"('6.42375 ', '-66.58973')"
191,"$261,921,244,843",110.60%,28.50%,16.5,Ho Chi Minh City,75.3,43.0,$0.73,Vietnamese,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",Vietnam,"('14.058324 ', '108.277199')"
192,"$26,914,402,224",93.60%,10.20%,42.9,Sanaa,66.1,164.0,NaN,Arabic,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",Yemen,"('15.552727 ', '48.516388')"
193,"$23,064,722,446",98.70%,4.10%,40.4,Lusaka,63.5,213.0,$0.24,English,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",Zambia,"('-13.133897 ', '27.849332')"
194,"$21,440,758,800",109.90%,10.00%,33.9,Harare,61.2,458.0,NaN,Shona,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",Zimbabwe,"('-19.015438 ', '29.154857')"

# Ejercicios Unión de Datos

Para realizar estos ejercicios deberéis usar el conjunto de datos de world-data-2023-part1.csv y el de world-data-2023-part2.csv.

---

Tienes a tu disposición dos conjuntos de datos, "world-data-2023-part1.csv" y "world-data-2023-part2.csv", que contienen información de una serie de indicadores y datos de distintos países. Tu tarea es explorar estos conjuntos de datos y determinar qué tienen en común en términos de columnas y datos.

Luego, debes crear un nuevo DataFrame que combine la información de ambos conjuntos de datos en un solo conjunto de datos. Para hacerlo, debes seleccionar el método de unión de Pandas que consideres más apropiado para esta situación y justificar por qué crees que ese método es el mejor en tu informe.

Asegúrate de realizar los siguientes pasos:

Explora y carga ambos conjuntos de datos en pandas DataFrames.

Identifica las columnas comunes entre los dos conjuntos de datos.

Utiliza el método de unión de Pandas que consideres más adecuado para combinar los datos de ambos años en un solo DataFrame.

Explica por qué elegiste ese método de unión y cómo se llevaron a cabo los pasos anteriores.

---

In [5]:
mergeado_inner = df_part1.merge(df_part2, left_on='Country', right_on = "country")
mergeado_inner.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

In [6]:
df_part1.shape

(195, 16)

In [7]:
df_part2.shape

(195, 19)

In [8]:
mergeado_inner.shape

(195, 35)

## Ejercicios de Limpieza

1. Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

In [9]:
mergeado_inner.drop(columns=["country"], inplace=True)

In [10]:
mergeado_inner.shape

(195, 34)

2. Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

No tengan espacios.

Estén en minúscula.

No tengan paréntesis, es decir, quitar "(%)", "(Km2)".

Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.

Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

In [11]:
columnas = mergeado_inner.columns
nuevas_columnas = {col: col.split("(")[0].strip().replace(" ", "_").replace("\n", "").replace(":", "").lower() for col in columnas}
mergeado_inner.rename(columns=nuevas_columnas, inplace = True)

In [12]:
nuevas_columnas

{'Country': 'country',
 'Density\n(P/Km2)': 'density',
 'Abbreviation': 'abbreviation',
 'Agricultural Land( %)': 'agricultural_land',
 'Land Area(Km2)': 'land_area',
 'Armed Forces size': 'armed_forces_size',
 'Birth Rate': 'birth_rate',
 'Calling Code': 'calling_code',
 'Capital/Major City': 'capital/major_city',
 'Co2-Emissions': 'co2-emissions',
 'CPI': 'cpi',
 'CPI Change (%)': 'cpi_change',
 'Currency-Code': 'currency-code',
 'Fertility Rate': 'fertility_rate',
 'Forested Area (%)': 'forested_area',
 'Gasoline Price': 'gasoline_price',
 'GDP': 'gdp',
 'Gross primary education enrollment (%)': 'gross_primary_education_enrollment',
 'Gross tertiary education enrollment (%)': 'gross_tertiary_education_enrollment',
 'Infant mortality': 'infant_mortality',
 'Largest city': 'largest_city',
 'Life expectancy': 'life_expectancy',
 'Maternal mortality ratio': 'maternal_mortality_ratio',
 'Minimum wage': 'minimum_wage',
 'Official language': 'official_language',
 'Out of pocket health expenditure': 'out_of_pocket_health_expenditure',
 'Physicians per thousand': 'physicians_per_thousand',
 'Population': 'population',
 'Population: Labor force participation (%)': 'population_labor_force_participation',
 'Tax revenue (%)': 'tax_revenue',
 'Total tax rate': 'total_tax_rate',
 'Unemployment rate': 'unemployment_rate',
 'Urban_population': 'urban_population',
 'coordinates': 'coordinates'}

In [13]:
mergeado_inner.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,...,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

3. La columnas coordinates tiene la latitud y la longitud en una sola columna. Crea dos columnas nuevas, una con la longitud y otra con la latitud. Una vez hecho, elimina la columna de coordinates.

In [14]:
mergeado_inner["coordinates"]

0        ('33.93911 ', '67.709953')
1       ('41.153332 ', '20.168331')
2        ('28.033886 ', '1.659626')
3        ('42.506285 ', '1.521801')
4      ('-11.202692 ', '17.873887')
                   ...
190       ('6.42375 ', '-66.58973')
191    ('14.058324 ', '108.277199')
192     ('15.552727 ', '48.516388')
193    ('-13.133897 ', '27.849332')
194    ('-19.015438 ', '29.154857')
Name: coordinates, Length: 195, dtype: object

In [15]:
mergeado_inner["coordinates"].str.split(",", expand = True)

                  0               1
0      ('33.93911 '    '67.709953')
1     ('41.153332 '    '20.168331')
2     ('28.033886 '     '1.659626')
3     ('42.506285 '     '1.521801')
4    ('-11.202692 '    '17.873887')
..              ...             ...
190     ('6.42375 '    '-66.58973')
191   ('14.058324 '   '108.277199')
192   ('15.552727 '    '48.516388')
193  ('-13.133897 '    '27.849332')
194  ('-19.015438 '    '29.154857')

[195 rows x 2 columns]

In [18]:
mergeado_inner[["latitud", "longitud"]] = mergeado_inner["coordinates"].str.split(",", expand = True).get([0,1])
mergeado_inner.head(2)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,...,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,coordinates,latitud,longitud
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')",('33.93911 ','67.709953')
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')",('41.153332 ','20.168331')

In [19]:
mergeado_inner.drop(columns=["coordinates"], inplace=True)
mergeado_inner.head(2)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,...,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitud,longitud
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",('33.93911 ','67.709953')
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",('41.153332 ','20.168331')

4. Las columnas unemployment_rate, total_tax_rate, tax_revenue, population_labor_force_participation, out_of_pocket_health_expenditure, gross_tertiary_education_enrollment, gross_primary_education_enrollment, forested_area, cpi_change, agricultural_land tienen "%". Elimina los "%" de los valores de las columnas.

5. Haz lo mismo para las columnas de gasoline_price, gdp, minimum_wage, pero eliminando "$".

6. Guarda el DataFrame para usarlo posteriormente.

---

## Ejercicios de Filtrado

1. Encuentra todos los países cuya mortalidad infantil esté entre 40 y 50 personas por kilómetro cuadrado.

2. Encuentra los países cuyas tasas de natalidad son mayores o iguales a 20 y su esperanza de vida es mayor de 75 años.

3. Encuentra las ciudades cuyos paises contienen la palabra "la" en su nombre.

4. Encuentra los países cuyos medicos por cada 1000 habitantes (physicians_per_thousand) sea mayores de 5.

5. Encuentra los países cuyatasa de fertilidad sea mayor a 6.

6. Encuentra los países cuya moneda es el euro (EUR) y tienen una tasa de natalidad superior al promedio.

7. Encuentra los países cuyas tasas de mortalidad infantil son superiores a 70.